### ISSUE TITLE
Sometimes the second FiveM client closes itself after starting

### ISSUE THREAD

**Issue by s1nyx** [Tuncion/multiple-fivem-clients#1]
Hi,

Sometimes (like maybe 10% of the time ?) when i start my second account with the bat file, the game is going to freeze after checking the date and shutdown itself. 

I am not the only one who had this issue. I think you should add in the README that this can happen so people know it really works if you restart it.

Have a nice day.

**Comment by Tuncion** [comment]
Hi,

thanks for the information. I will adjust the ReadMe once.

have a nice day too and thanks again!
